### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by micros123** [TobiasHoll/ccextract#2]
After installing requirements and running the script I get the following error:

> Either the database is corrupted or your version of the sqlite3 module is too old.

I'm on MacOS High Sierra, Python 2.7.10 which includes sqlite.
Would be great if you manage to fix this or tell me whats wrong. Maybe the iTunes backup format changed?

**Comment by TobiasHoll** [comment]
I vaguely remember encountering an issue like that before. I don't remember why exactly, but I think for some reason the sqlite module in Python 2 was unable to read the database.

```python
import sqlite3 # Use the newest version possible -> this has to be a py3k tool
```

I think the best course of action is to just try running it in Python 3 instead. If the database format has stayed the same since I wrote this (which admittedly is a big if), it should still work. Please do let me know if that helps.
